/**
 * Quick-add modal for inventory masters (category, subcategory, unit, item).
 * Codes are auto-generated by the API when omitted.
 */
import { useState } from "react";
import {
  api,
  type ItemCategoryResponse,
  type ItemSubcategoryResponse,
  type ItemUnitResponse,
  type InventoryItemResponse,
} from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { X } from "lucide-react";
import { logApiError } from "@/utils/logApiError";
import { erpControlFocusClass } from "@/components/app/listPageLayout";
import { cn } from "@/lib/utils";

export type MasterQuickAddType = "category" | "subcategory" | "unit" | "item";

type CreatedRecord =
  | ItemCategoryResponse
  | ItemSubcategoryResponse
  | ItemUnitResponse
  | InventoryItemResponse;

export type MasterQuickAddModalProps = {
  open: boolean;
  onClose: () => void;
  masterType: MasterQuickAddType;
  /** For subcategory / item: pre-selected category */
  defaultCategoryId?: number;
  categories: { id: number; name: string }[];
  units: { id: number; name: string }[];
  subcategories: { id: number; name: string; category_id: number }[];
  onCreated: (record: CreatedRecord) => void;
};

export function MasterQuickAddModal({
  open,
  onClose,
  masterType,
  defaultCategoryId,
  categories,
  units,
  subcategories,
  onCreated,
}: MasterQuickAddModalProps) {
  const [name, setName] = useState("");
  const [categoryId, setCategoryId] = useState(defaultCategoryId ?? categories[0]?.id ?? 0);
  const [subcategoryId, setSubcategoryId] = useState<number | "">("");
  const [unitId, setUnitId] = useState(units[0]?.id ?? 0);
  const [defaultCost, setDefaultCost] = useState("0");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  if (!open) return null;

  const title =
    masterType === "category"
      ? "Add category"
      : masterType === "subcategory"
        ? "Add subcategory"
        : masterType === "unit"
          ? "Add unit"
          : "Add item";

  const reset = () => {
    setName("");
    setCategoryId(defaultCategoryId ?? categories[0]?.id ?? 0);
    setSubcategoryId("");
    setUnitId(units[0]?.id ?? 0);
    setDefaultCost("0");
    setError("");
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setBusy(true);
    try {
      if (masterType === "category") {
        const r = await api.createInventoryItemCategory({ name: name.trim() });
        onCreated(r);
      } else if (masterType === "subcategory") {
        if (!categoryId) {
          setError("Select a category.");
          return;
        }
        const r = await api.createInventoryItemSubcategory({
          category_id: categoryId,
          name: name.trim(),
        });
        onCreated(r);
      } else if (masterType === "unit") {
        const r = await api.createInventoryItemUnit({ name: name.trim() });
        onCreated(r);
      } else {
        if (!categoryId || !unitId) {
          setError("Select category and unit.");
          return;
        }
        const r = await api.createInventoryItem({
          name: name.trim(),
          category_id: categoryId,
          subcategory_id: subcategoryId === "" ? null : subcategoryId,
          unit_id: unitId,
          default_cost: defaultCost || "0",
        });
        onCreated(r);
      }
      reset();
      onClose();
    } catch (err) {
      logApiError("MasterQuickAddModal.submit", err);
      setError(err instanceof Error ? err.message : "Failed to save");
    } finally {
      setBusy(false);
    }
  };

  const subsForCat = subcategories.filter((s) => s.category_id === categoryId);

  return (
    <div
      className="fixed inset-0 z-[60] flex items-center justify-center bg-surface-inverse/50 p-4"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="master-quick-add-title"
    >
      <Card className="w-full max-w-md shadow-xl" onClick={(e) => e.stopPropagation()}>
        <CardHeader className="flex flex-row items-center justify-between border-b border-border-subtle pb-3">
          <CardTitle id="master-quick-add-title" className="text-lg">
            {title}
          </CardTitle>
          <Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="Close">
            <X className="h-4 w-4" />
          </Button>
        </CardHeader>
        <CardContent className="pt-4">
          <form onSubmit={handleSubmit} className="space-y-3">
            {error ? (
              <div className="rounded-md border border-status-danger/30 bg-status-danger-subtle px-3 py-2 text-sm text-status-danger-foreground">
                {error}
              </div>
            ) : null}
            {(masterType === "subcategory" || masterType === "item") && (
              <div>
                <label className="mb-1 block text-xs font-medium text-text-muted">Category</label>
                <select
                  className={cn(
                    "w-full rounded-lg border border-border-strong px-3 py-2 text-sm",
                    erpControlFocusClass,
                  )}
                  value={categoryId}
                  onChange={(e) => {
                    setCategoryId(Number(e.target.value));
                    setSubcategoryId("");
                  }}
                  required
                >
                  {categories.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </select>
              </div>
            )}
            {masterType === "item" && (
              <>
                <div>
                  <label className="mb-1 block text-xs font-medium text-text-muted">Subcategory (optional)</label>
                  <select
                    className={cn(
                      "w-full rounded-lg border border-border-strong px-3 py-2 text-sm",
                      erpControlFocusClass,
                    )}
                    value={subcategoryId === "" ? "" : String(subcategoryId)}
                    onChange={(e) => setSubcategoryId(e.target.value ? Number(e.target.value) : "")}
                  >
                    <option value="">None</option>
                    {subsForCat.map((s) => (
                      <option key={s.id} value={s.id}>
                        {s.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="mb-1 block text-xs font-medium text-text-muted">Unit</label>
                  <select
                    className={cn(
                      "w-full rounded-lg border border-border-strong px-3 py-2 text-sm",
                      erpControlFocusClass,
                    )}
                    value={unitId}
                    onChange={(e) => setUnitId(Number(e.target.value))}
                    required
                  >
                    {units.map((u) => (
                      <option key={u.id} value={u.id}>
                        {u.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="mb-1 block text-xs font-medium text-text-muted">Default cost (optional)</label>
                  <input
                    className={cn(
                      "w-full rounded-lg border border-border-strong px-3 py-2 text-sm",
                      erpControlFocusClass,
                    )}
                    value={defaultCost}
                    onChange={(e) => setDefaultCost(e.target.value)}
                  />
                </div>
              </>
            )}
            <div>
              <label className="mb-1 block text-xs font-medium text-text-muted">
                {masterType === "unit" ? "Unit name" : "Name"}
              </label>
              <input
                className={cn(
                  "w-full rounded-lg border border-border-strong px-3 py-2 text-sm",
                  erpControlFocusClass,
                )}
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder={masterType === "category" ? "e.g. Fabric" : "Display name"}
                required
                autoFocus
              />
            </div>
            <div className="flex justify-end gap-2 pt-2">
              <Button type="button" variant="outline" onClick={onClose} disabled={busy}>
                Cancel
              </Button>
              <Button type="submit" disabled={busy}>
                {busy ? "Saving…" : "Create"}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
