import type { LegalDocument } from "./types";

/** Standalone AI usage disclaimer—read alongside Terms and Privacy Policy. */
export const aiDisclaimerDocument: LegalDocument = {
  id: "ai-disclaimer",
  version: "1.0.0",
  lastUpdated: "2026-04-04",
  title: "Artificial Intelligence (AI) Usage Disclaimer",
  intro:
    "This AI Usage Disclaimer applies to any artificial intelligence, machine learning, or automated suggestion features offered in or with Prime7 ERP (the \"AI Features\"). By using AI Features, you acknowledge and agree to this Disclaimer in addition to our Terms of Service and Privacy Policy.",
  sections: [
    {
      id: "advisory",
      title: "1. Advisory and Informational Use Only",
      blocks: [
        {
          kind: "p",
          text: "AI Features are provided solely for assistance, efficiency, and informational purposes. They do not constitute professional advice of any kind—including legal, tax, accounting, audit, investment, regulatory, medical, or safety advice. You must obtain advice from qualified professionals before making decisions that could affect your legal rights, financial statements, tax filings, regulatory filings, contracts, or operational safety.",
        },
      ],
    },
    {
      id: "accuracy",
      title: "2. No Warranty of Accuracy or Completeness",
      blocks: [
        {
          kind: "p",
          text: "AI outputs may be incorrect, incomplete, outdated, biased, or nonsensical. Prime7 ERP, its affiliates, and licensors make no representation or warranty that AI outputs are accurate, reliable, suitable for your use case, or free from error. AI Features are provided \"AS IS\" and \"AS AVAILABLE\" without warranties of any kind, to the maximum extent permitted by law.",
        },
      ],
    },
    {
      id: "validation",
      title: "3. Your Duty to Validate",
      blocks: [
        {
          kind: "p",
          text: "You are solely responsible for reviewing, verifying, and validating all AI outputs before relying on them. You must independently confirm figures, inventory counts, financial impacts, compliance obligations, and any data extracted from documents. You must not treat AI output as a substitute for human judgment, internal controls, or statutory record-keeping requirements.",
        },
      ],
    },
    {
      id: "no-auto-posting",
      title: "4. No Autonomous Transaction Posting",
      blocks: [
        {
          kind: "p",
          text: "AI Features do not autonomously create, authorize, or post accounting entries, payments, journal vouchers, inventory adjustments, production orders, payroll transactions, or other business transactions. Any transactional effect in the system requires explicit human action through the Service's normal workflows and controls (subject to your configuration and permissions). If future features offer automation, they will be subject to explicit configuration and audit trails.",
        },
      ],
    },
    {
      id: "liability",
      title: "5. Limitation of Liability Relating to AI",
      blocks: [
        {
          kind: "p",
          text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, PRIME7 ERP AND ITS AFFILIATES WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE (INCLUDING DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES) ARISING OUT OF OR RELATED TO YOUR USE OF OR RELIANCE ON AI FEATURES OR ANY DECISION MADE OR NOT MADE BASED ON AI OUTPUTS, INCLUDING LOST PROFITS, LOST REVENUE, BUSINESS INTERRUPTION, LOSS OF GOODWILL, OR LOSS OF DATA—EVEN IF ADVISED OF THE POSSIBILITY.",
        },
        {
          kind: "p",
          text: "If any limitation is not enforceable, our total liability for AI-related claims remains subject to the aggregate cap in the Terms of Service unless mandatory law provides otherwise.",
        },
      ],
    },
    {
      id: "third-party",
      title: "6. Third-Party Models and Services",
      blocks: [
        {
          kind: "p",
          text: "AI Features may rely on third-party model providers and infrastructure. Their availability, behavior, and policies may change. Prime7 is not responsible for third-party service outages, model changes, or content generated by third-party systems beyond our reasonable control.",
        },
      ],
    },
    {
      id: "data",
      title: "7. Data Processing",
      blocks: [
        {
          kind: "p",
          text: "Use of AI Features may involve processing prompts, contextual data, and outputs as described in our Privacy Policy and Data Processing Agreement. Do not submit highly sensitive personal data or regulated secrets to AI Features unless you have assessed legality and your internal policies permit it.",
        },
      ],
    },
    {
      id: "acceptance",
      title: "8. Acceptance",
      blocks: [
        {
          kind: "p",
          text: "If you do not agree with this Disclaimer, you must not use AI Features. Continued use after we post updates constitutes acceptance of the revised Disclaimer.",
        },
      ],
    },
  ],
};
