import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const REPORTS_DIR = path.join(process.cwd(), 'generated-reports');

export function ensureReportsDir(): void {
  if (!fs.existsSync(REPORTS_DIR)) {
    fs.mkdirSync(REPORTS_DIR, { recursive: true });
  }
}

export function getReportsDir(): string {
  return REPORTS_DIR;
}

export interface PdfReportData {
  reportName: string;
  reportType: string;
  category: string;
  module: string;
  generatedBy: string;
  tenantName: string;
  data: Record<string, any>[];
  insights?: Array<{ title: string; description: string; importance: string; recommendation: string }>;
}

export async function generateReportPdf(data: PdfReportData, outputPath: string): Promise<{ fileSize: number }> {
  return new Promise((resolve, reject) => {
    try {
      ensureReportsDir();
      
      const doc = new PDFDocument({ 
        size: 'A4', 
        margin: 50,
        bufferPages: true,
        info: {
          Title: data.reportName,
          Author: data.generatedBy,
          Subject: `${data.category} - ${data.module}`,
          Creator: 'PrimeX ERP System',
        }
      });
      
      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);
      
      doc.fontSize(20).font('Helvetica-Bold').text('PrimeX ERP', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(16).text(data.reportName, { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica')
        .text(`Category: ${data.category || 'N/A'} | Module: ${data.module || 'N/A'} | Type: ${data.reportType || 'Custom'}`, { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(9).fillColor('#666666')
        .text(`Generated by: ${data.generatedBy} | Tenant: ${data.tenantName} | Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`, { align: 'center' });
      doc.fillColor('#000000');
      
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
      doc.moveDown(1);
      
      if (data.data && data.data.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Report Data', { underline: true });
        doc.moveDown(0.5);
        
        const columns = Object.keys(data.data[0]);
        const maxCols = Math.min(columns.length, 6);
        const selectedCols = columns.slice(0, maxCols);
        const colWidth = (545 - 50) / maxCols;
        
        doc.fontSize(8).font('Helvetica-Bold');
        let xPos = 50;
        selectedCols.forEach((col) => {
          const label = col.replace(/_/g, ' ').replace(/([A-Z])/g, ' $1').trim();
          doc.text(label.substring(0, 15), xPos, doc.y, { width: colWidth - 5, align: 'left', continued: false });
          xPos += colWidth;
        });
        doc.moveDown(0.3);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#dddddd');
        doc.moveDown(0.2);
        
        doc.font('Helvetica').fontSize(7);
        const maxRows = Math.min(data.data.length, 50);
        for (let i = 0; i < maxRows; i++) {
          const row = data.data[i];
          const startY = doc.y;
          
          if (startY > 700) {
            doc.addPage();
          }
          
          xPos = 50;
          selectedCols.forEach((col) => {
            let val = row[col];
            if (val === null || val === undefined) val = '-';
            else if (typeof val === 'object') val = JSON.stringify(val).substring(0, 20);
            else val = String(val).substring(0, 20);
            doc.text(val, xPos, doc.y, { width: colWidth - 5, align: 'left', continued: false });
            xPos += colWidth;
          });
          doc.moveDown(0.1);
          
          if (i % 2 === 1) {
            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#f0f0f0');
          }
        }
        
        if (data.data.length > maxRows) {
          doc.moveDown(0.5);
          doc.fontSize(8).fillColor('#999999')
            .text(`Showing ${maxRows} of ${data.data.length} records`, { align: 'center' });
          doc.fillColor('#000000');
        }
        
        doc.moveDown(1);
        doc.fontSize(10).font('Helvetica')
          .text(`Total Records: ${data.data.length}`, { align: 'left' });
      } else {
        doc.fontSize(12).text('No data available for this report.', { align: 'center' });
      }
      
      if (data.insights && data.insights.length > 0) {
        doc.addPage();
        doc.fontSize(14).font('Helvetica-Bold').text('AI-Generated Insights', { underline: true });
        doc.moveDown(0.5);
        
        data.insights.forEach((insight, index) => {
          if (doc.y > 680) doc.addPage();
          
          doc.fontSize(11).font('Helvetica-Bold')
            .text(`${index + 1}. ${insight.title}`, { continued: false });
          
          const importanceColor = insight.importance === 'High' ? '#dc2626' : 
                                  insight.importance === 'Medium' ? '#f59e0b' : '#22c55e';
          doc.fontSize(8).fillColor(importanceColor)
            .text(`Importance: ${insight.importance}`, { continued: false });
          doc.fillColor('#000000');
          
          doc.moveDown(0.2);
          doc.fontSize(9).font('Helvetica')
            .text(insight.description, { indent: 10 });
          doc.moveDown(0.2);
          doc.fontSize(9).font('Helvetica-Oblique')
            .text(`Recommendation: ${insight.recommendation}`, { indent: 10 });
          doc.moveDown(0.5);
        });
      }
      
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fontSize(7).fillColor('#999999')
          .text(`Page ${i + 1} of ${pageCount} | PrimeX ERP - Confidential`, 50, 780, { align: 'center', width: 495 });
      }
      doc.fillColor('#000000');
      
      doc.end();
      
      writeStream.on('finish', () => {
        const stats = fs.statSync(outputPath);
        resolve({ fileSize: stats.size });
      });
      
      writeStream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
}
