server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /admin/assets/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /admin/ {
    try_files $uri $uri/ /index.html;
  }

  location = /admin {
    return 301 /admin/;
  }
}
