import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors, DragEndEvent } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';

// Widget definition type
interface Widget {
  id: string;
  name: string;
  description: string;
  icon: string;
  size: 'small' | 'medium' | 'large' | 'full';
  defaultLocation: 'main' | 'sidebar';
  isPremium: boolean;
  isActive: boolean;
  component: string;
}

// Available widgets in the system
const availableWidgets: Widget[] = [
  {
    id: 'kpi-cards',
    name: 'KPI Overview',
    description: 'Key performance indicators and metrics summary',
    icon: 'dashboard',
    size: 'full',
    defaultLocation: 'main',
    isPremium: false,
    isActive: true,
    component: 'KPICards'
  },
  {
    id: 'ai-insights',
    name: 'AI Insights',
    description: 'Intelligent insights and alerts generated by AI',
    icon: 'lightbulb',
    size: 'full',
    defaultLocation: 'main',
    isPremium: false,
    isActive: true,
    component: 'AIInsights'
  },
  {
    id: 'production-trends',
    name: 'Production Trends',
    description: 'Visual charts of production metrics over time',
    icon: 'trending_up',
    size: 'medium',
    defaultLocation: 'main',
    isPremium: false,
    isActive: true,
    component: 'ProductionTrends'
  },
  {
    id: 'inventory-forecast',
    name: 'Inventory Forecast',
    description: 'Predictive inventory analysis and recommendations',
    icon: 'inventory',
    size: 'large',
    defaultLocation: 'main',
    isPremium: true,
    isActive: true,
    component: 'InventoryForecast'
  },
  {
    id: 'order-status',
    name: 'Order Status',
    description: 'Current production orders and their statuses',
    icon: 'view_list',
    size: 'medium',
    defaultLocation: 'main',
    isPremium: false,
    isActive: true,
    component: 'OrderStatus'
  },
  {
    id: 'tasks-list',
    name: 'Tasks List',
    description: 'Personal and team task manager',
    icon: 'task_alt',
    size: 'small',
    defaultLocation: 'sidebar',
    isPremium: false,
    isActive: true,
    component: 'TasksList'
  },
  {
    id: 'mood-productivity',
    name: 'Mood & Productivity',
    description: 'AI-powered mood and productivity tracking',
    icon: 'sentiment_satisfied',
    size: 'medium',
    defaultLocation: 'main',
    isPremium: true,
    isActive: true,
    component: 'MoodProductivity'
  },
  {
    id: 'calendar-events',
    name: 'Calendar Events',
    description: 'Upcoming meetings and events',
    icon: 'event',
    size: 'small',
    defaultLocation: 'sidebar',
    isPremium: false,
    isActive: true,
    component: 'CalendarEvents'
  },
  {
    id: 'achievement-badges',
    name: 'Achievement Badges',
    description: 'Gamified performance tracking system',
    icon: 'emoji_events',
    size: 'large',
    defaultLocation: 'main',
    isPremium: true,
    isActive: true,
    component: 'AchievementBadges'
  },
  {
    id: 'ai-vision-analysis',
    name: 'AI Vision Analysis',
    description: 'Computer vision quality control insights',
    icon: 'visibility',
    size: 'medium',
    defaultLocation: 'main',
    isPremium: true,
    isActive: false,
    component: 'AIImageAnalysis'
  },
  {
    id: 'supply-chain-status',
    name: 'Supply Chain',
    description: 'Supply chain health and status',
    icon: 'inventory_2',
    size: 'small',
    defaultLocation: 'sidebar',
    isPremium: false,
    isActive: true,
    component: 'SupplyChainStatus'
  },
  {
    id: 'sustainability-metrics',
    name: 'Sustainability',
    description: 'Environmental impact and sustainability KPIs',
    icon: 'eco',
    size: 'medium',
    defaultLocation: 'main',
    isPremium: true,
    isActive: false,
    component: 'SustainabilityMetrics'
  }
];

// Sortable Widget Item component
const SortableWidgetItem = ({ widget, isEditing }: { widget: Widget, isEditing: boolean }) => {
  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: widget.id });
  
  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };
  
  return (
    <div
      ref={setNodeRef}
      style={style}
      {...attributes}
      className={`border rounded-lg bg-white mb-4 shadow-sm ${isEditing ? 'cursor-move hover:border-primary' : ''}`}
    >
      <div className="p-3 border-b flex justify-between items-center bg-neutral-50">
        <div className="flex items-center">
          <span className="material-icons text-primary mr-2">{widget.icon}</span>
          <span className="font-medium">{widget.name}</span>
        </div>
        
        {isEditing && (
          <div className="flex items-center">
            {widget.isPremium && (
              <Badge className="mr-2 bg-amber-100 text-amber-800 border-amber-200">Premium</Badge>
            )}
            <div className="flex" {...listeners}>
              <button className="p-1 text-neutral-dark hover:text-primary">
                <span className="material-icons text-sm">drag_indicator</span>
              </button>
            </div>
          </div>
        )}
      </div>
      
      {isEditing && (
        <div className="p-3 text-sm text-neutral-dark">
          {widget.description}
        </div>
      )}
    </div>
  );
};

// Widget Gallery Item component (for adding new widgets)
const WidgetGalleryItem = ({ widget, onAdd }: { widget: Widget, onAdd: (widget: Widget) => void }) => {
  return (
    <div className="border rounded-lg bg-white hover:border-primary transition-colors cursor-pointer" 
         onClick={() => onAdd(widget)}>
      <div className="p-3 border-b flex justify-between items-center">
        <div className="flex items-center">
          <span className="material-icons text-primary mr-2">{widget.icon}</span>
          <span className="font-medium">{widget.name}</span>
        </div>
        
        <div className="flex items-center">
          {widget.isPremium && (
            <Badge className="mr-2 bg-amber-100 text-amber-800 border-amber-200">Premium</Badge>
          )}
          <button className="p-1 bg-primary text-white rounded-full">
            <span className="material-icons text-sm">add</span>
          </button>
        </div>
      </div>
      
      <div className="p-3">
        <p className="text-sm text-neutral-dark mb-2">{widget.description}</p>
        <Badge className={`${
          widget.size === 'small' ? 'bg-blue-100 text-blue-800' :
          widget.size === 'medium' ? 'bg-purple-100 text-purple-800' :
          widget.size === 'large' ? 'bg-orange-100 text-orange-800' :
          'bg-green-100 text-green-800'
        }`}>
          {widget.size.charAt(0).toUpperCase() + widget.size.slice(1)} Size
        </Badge>
      </div>
    </div>
  );
};

export const CustomizableLayout = () => {
  const [isEditing, setIsEditing] = useState(false);
  const [mainWidgets, setMainWidgets] = useState<Widget[]>([]);
  const [sidebarWidgets, setSidebarWidgets] = useState<Widget[]>([]);
  const [availableToAdd, setAvailableToAdd] = useState<Widget[]>([]);
  const [layoutName, setLayoutName] = useState('Default Layout');
  const [showGallery, setShowGallery] = useState(false);
  
  // Initialize with default widgets
  useEffect(() => {
    // Filter to only active widgets for initial display
    const activeWidgets = availableWidgets.filter(widget => widget.isActive);
    
    setMainWidgets(activeWidgets.filter(widget => widget.defaultLocation === 'main'));
    setSidebarWidgets(activeWidgets.filter(widget => widget.defaultLocation === 'sidebar'));
    setAvailableToAdd(availableWidgets.filter(widget => !widget.isActive));
  }, []);
  
  // Set up DnD sensors
  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );
  
  // Handle drag end for main widgets
  const handleMainDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    
    if (active.id !== over?.id) {
      setMainWidgets((items) => {
        const oldIndex = items.findIndex(item => item.id === active.id);
        const newIndex = items.findIndex(item => item.id === over?.id);
        
        return arrayMove(items, oldIndex, newIndex);
      });
    }
  };
  
  // Handle drag end for sidebar widgets
  const handleSidebarDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    
    if (active.id !== over?.id) {
      setSidebarWidgets((items) => {
        const oldIndex = items.findIndex(item => item.id === active.id);
        const newIndex = items.findIndex(item => item.id === over?.id);
        
        return arrayMove(items, oldIndex, newIndex);
      });
    }
  };
  
  // Add widget from gallery to dashboard
  const addWidget = (widget: Widget) => {
    const updatedWidget = { ...widget, isActive: true };
    
    if (widget.defaultLocation === 'main') {
      setMainWidgets([...mainWidgets, updatedWidget]);
    } else {
      setSidebarWidgets([...sidebarWidgets, updatedWidget]);
    }
    
    setAvailableToAdd(availableToAdd.filter(w => w.id !== widget.id));
  };
  
  // Remove widget from dashboard
  const removeWidget = (widget: Widget) => {
    const updatedWidget = { ...widget, isActive: false };
    
    if (widget.defaultLocation === 'main') {
      setMainWidgets(mainWidgets.filter(w => w.id !== widget.id));
    } else {
      setSidebarWidgets(sidebarWidgets.filter(w => w.id !== widget.id));
    }
    
    setAvailableToAdd([...availableToAdd, updatedWidget]);
  };
  
  // Save layout configuration
  const saveLayout = () => {
    // In a real app, this would save to a backend API
    setIsEditing(false);
    
    // Show success message
    alert('Layout saved successfully!');
  };
  
  // Load a saved layout
  const loadLayout = (layoutName: string) => {
    // In a real app, this would load from a backend API
    
    // For demo purposes, we'll just toggle between two predefined layouts
    if (layoutName === 'Production Focus') {
      // Reset to default first
      const activeWidgets = availableWidgets.filter(widget => widget.isActive);
      setMainWidgets(activeWidgets.filter(widget => 
        ['kpi-cards', 'production-trends', 'inventory-forecast', 'order-status'].includes(widget.id)
      ));
      setSidebarWidgets(activeWidgets.filter(widget => 
        ['tasks-list', 'calendar-events'].includes(widget.id)
      ));
    } else if (layoutName === 'Analytics Focus') {
      // Reset to default first
      const activeWidgets = availableWidgets.filter(widget => widget.isActive);
      setMainWidgets(activeWidgets.filter(widget => 
        ['kpi-cards', 'ai-insights', 'mood-productivity', 'achievement-badges'].includes(widget.id)
      ));
      setSidebarWidgets(activeWidgets.filter(widget => 
        ['tasks-list', 'calendar-events', 'supply-chain-status'].includes(widget.id)
      ));
    }
    
    setLayoutName(layoutName);
    setIsEditing(false);
  };
  
  return (
    <Card className="overflow-hidden border-primary/10 shadow-md bg-white/90 backdrop-blur-sm mb-6">
      <CardHeader className="bg-gradient-to-r from-primary/5 to-primary/10 pb-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div>
            <CardTitle className="text-lg font-medium flex items-center mb-1">
              <span className="material-icons mr-2 text-primary">dashboard_customize</span>
              Dashboard Layout
            </CardTitle>
            <p className="text-sm text-neutral-dark">
              Current layout: <span className="font-medium">{layoutName}</span>
            </p>
          </div>
          
          <div className="flex gap-2">
            {isEditing ? (
              <>
                <button 
                  className="text-sm bg-neutral-100 hover:bg-neutral-200 px-3 py-1.5 rounded-md flex items-center"
                  onClick={() => {
                    setIsEditing(false);
                    setShowGallery(false);
                  }}
                >
                  <span className="material-icons text-sm mr-1">close</span>
                  Cancel
                </button>
                <button 
                  className="text-sm bg-primary text-white hover:bg-primary-dark px-3 py-1.5 rounded-md flex items-center"
                  onClick={saveLayout}
                >
                  <span className="material-icons text-sm mr-1">save</span>
                  Save Layout
                </button>
              </>
            ) : (
              <>
                <button 
                  className="text-sm bg-neutral-100 hover:bg-neutral-200 px-3 py-1.5 rounded-md flex items-center"
                  onClick={() => setIsEditing(true)}
                >
                  <span className="material-icons text-sm mr-1">edit</span>
                  Customize
                </button>
                <select 
                  className="text-sm bg-neutral-100 hover:bg-neutral-200 px-3 py-1.5 rounded-md"
                  onChange={(e) => loadLayout(e.target.value)}
                  value={layoutName}
                >
                  <option value="Default Layout">Default Layout</option>
                  <option value="Production Focus">Production Focus</option>
                  <option value="Analytics Focus">Analytics Focus</option>
                </select>
              </>
            )}
          </div>
        </div>
      </CardHeader>
      
      <CardContent className="pt-4">
        {isEditing ? (
          <>
            <div className="p-4 mb-4 bg-primary/5 border border-primary/20 rounded-lg">
              <h3 className="font-medium mb-2 flex items-center">
                <span className="material-icons text-primary mr-2">info</span>
                Customization Mode
              </h3>
              <p className="text-sm text-neutral-dark mb-3">
                Drag and drop widgets to reorder them. Click "Add Widgets" to add more widgets to your dashboard.
              </p>
              
              <div className="flex justify-between">
                <div>
                  <Badge className="bg-blue-100 text-blue-800 mr-2">Small</Badge>
                  <Badge className="bg-purple-100 text-purple-800 mr-2">Medium</Badge>
                  <Badge className="bg-orange-100 text-orange-800 mr-2">Large</Badge>
                  <Badge className="bg-green-100 text-green-800">Full Width</Badge>
                </div>
                
                <button 
                  className="text-sm bg-primary text-white px-3 py-1 rounded-md flex items-center"
                  onClick={() => setShowGallery(!showGallery)}
                >
                  <span className="material-icons text-sm mr-1">add</span>
                  {showGallery ? 'Hide Gallery' : 'Add Widgets'}
                </button>
              </div>
            </div>
            
            {showGallery && (
              <div className="mb-6">
                <h3 className="font-medium mb-3">Widget Gallery</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {availableToAdd.map(widget => (
                    <WidgetGalleryItem key={widget.id} widget={widget} onAdd={addWidget} />
                  ))}
                  
                  {availableToAdd.length === 0 && (
                    <div className="col-span-full text-center p-4 bg-neutral-50 rounded-lg">
                      <p className="text-neutral-dark">All available widgets are already on your dashboard.</p>
                    </div>
                  )}
                </div>
              </div>
            )}
            
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              <div className="lg:col-span-2">
                <h3 className="font-medium mb-2">Main Content</h3>
                
                <DndContext 
                  sensors={sensors}
                  collisionDetection={closestCenter}
                  onDragEnd={handleMainDragEnd}
                >
                  <SortableContext 
                    items={mainWidgets.map(w => w.id)}
                    strategy={verticalListSortingStrategy}
                  >
                    {mainWidgets.map(widget => (
                      <div key={widget.id} className="relative">
                        <SortableWidgetItem widget={widget} isEditing={true} />
                        <button 
                          className="absolute top-3 right-3 p-1 bg-red-100 text-red-700 rounded-full hover:bg-red-200"
                          onClick={() => removeWidget(widget)}
                        >
                          <span className="material-icons text-sm">delete</span>
                        </button>
                      </div>
                    ))}
                  </SortableContext>
                </DndContext>
                
                {mainWidgets.length === 0 && (
                  <div className="border border-dashed rounded-lg p-8 text-center text-neutral-dark">
                    <span className="material-icons text-4xl mb-2">dashboard</span>
                    <p>Drag widgets here or add from the gallery</p>
                  </div>
                )}
              </div>
              
              <div>
                <h3 className="font-medium mb-2">Sidebar</h3>
                
                <DndContext 
                  sensors={sensors}
                  collisionDetection={closestCenter}
                  onDragEnd={handleSidebarDragEnd}
                >
                  <SortableContext 
                    items={sidebarWidgets.map(w => w.id)}
                    strategy={verticalListSortingStrategy}
                  >
                    {sidebarWidgets.map(widget => (
                      <div key={widget.id} className="relative">
                        <SortableWidgetItem widget={widget} isEditing={true} />
                        <button 
                          className="absolute top-3 right-3 p-1 bg-red-100 text-red-700 rounded-full hover:bg-red-200"
                          onClick={() => removeWidget(widget)}
                        >
                          <span className="material-icons text-sm">delete</span>
                        </button>
                      </div>
                    ))}
                  </SortableContext>
                </DndContext>
                
                {sidebarWidgets.length === 0 && (
                  <div className="border border-dashed rounded-lg p-8 text-center text-neutral-dark">
                    <span className="material-icons text-4xl mb-2">dashboard</span>
                    <p>Drag widgets here or add from the gallery</p>
                  </div>
                )}
              </div>
            </div>
          </>
        ) : (
          <div>
            <Tabs defaultValue="current">
              <TabsList>
                <TabsTrigger value="current">Current Layout</TabsTrigger>
                <TabsTrigger value="templates">Layout Templates</TabsTrigger>
                <TabsTrigger value="saved">Saved Layouts</TabsTrigger>
              </TabsList>
              
              <TabsContent value="current" className="pt-4">
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  <div className="lg:col-span-2">
                    <h3 className="font-medium mb-3">Main Content</h3>
                    <div className="space-y-3">
                      {mainWidgets.map(widget => (
                        <div key={widget.id} className="border rounded-lg bg-white shadow-sm overflow-hidden">
                          <div className="p-3 border-b flex justify-between items-center bg-neutral-50">
                            <div className="flex items-center">
                              <span className="material-icons text-primary mr-2">{widget.icon}</span>
                              <span className="font-medium">{widget.name}</span>
                            </div>
                            
                            {widget.isPremium && (
                              <Badge className="bg-amber-100 text-amber-800 border-amber-200">Premium</Badge>
                            )}
                          </div>
                          <div className="p-3 text-sm text-neutral-dark">
                            {widget.description}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="font-medium mb-3">Sidebar</h3>
                    <div className="space-y-3">
                      {sidebarWidgets.map(widget => (
                        <div key={widget.id} className="border rounded-lg bg-white shadow-sm overflow-hidden">
                          <div className="p-3 border-b flex justify-between items-center bg-neutral-50">
                            <div className="flex items-center">
                              <span className="material-icons text-primary mr-2">{widget.icon}</span>
                              <span className="font-medium">{widget.name}</span>
                            </div>
                            
                            {widget.isPremium && (
                              <Badge className="bg-amber-100 text-amber-800 border-amber-200">Premium</Badge>
                            )}
                          </div>
                          <div className="p-3 text-sm text-neutral-dark">
                            {widget.description}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="templates" className="pt-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="border rounded-lg p-4 hover:border-primary cursor-pointer">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h3 className="font-medium">Default Layout</h3>
                        <p className="text-sm text-neutral-dark">Balanced view of all modules</p>
                      </div>
                      <Badge>Current</Badge>
                    </div>
                    <div className="bg-neutral-100 h-32 rounded-md mb-3 overflow-hidden">
                      <div className="flex h-full">
                        <div className="w-2/3 p-1">
                          <div className="bg-primary/20 h-6 w-full mb-1 rounded"></div>
                          <div className="bg-primary/20 h-6 w-full mb-1 rounded"></div>
                          <div className="flex h-16 gap-1">
                            <div className="bg-primary/20 w-1/2 rounded"></div>
                            <div className="bg-primary/20 w-1/2 rounded"></div>
                          </div>
                        </div>
                        <div className="w-1/3 p-1">
                          <div className="bg-primary/20 h-10 w-full mb-1 rounded"></div>
                          <div className="bg-primary/20 h-10 w-full mb-1 rounded"></div>
                          <div className="bg-primary/20 h-6 w-full rounded"></div>
                        </div>
                      </div>
                    </div>
                    <button 
                      className="w-full px-3 py-1.5 bg-neutral-100 hover:bg-neutral-200 rounded-md text-sm"
                      onClick={() => loadLayout('Default Layout')}
                    >
                      Load Template
                    </button>
                  </div>
                  
                  <div className="border rounded-lg p-4 hover:border-primary cursor-pointer">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h3 className="font-medium">Production Focus</h3>
                        <p className="text-sm text-neutral-dark">Emphasizes production metrics</p>
                      </div>
                    </div>
                    <div className="bg-neutral-100 h-32 rounded-md mb-3 overflow-hidden">
                      <div className="flex h-full">
                        <div className="w-2/3 p-1">
                          <div className="bg-primary/20 h-6 w-full mb-1 rounded"></div>
                          <div className="flex h-10 gap-1 mb-1">
                            <div className="bg-primary/40 w-1/2 rounded"></div>
                            <div className="bg-primary/40 w-1/2 rounded"></div>
                          </div>
                          <div className="bg-primary/40 h-10 w-full rounded"></div>
                        </div>
                        <div className="w-1/3 p-1">
                          <div className="bg-primary/20 h-15 w-full mb-1 rounded"></div>
                          <div className="bg-primary/20 h-12 w-full rounded"></div>
                        </div>
                      </div>
                    </div>
                    <button 
                      className="w-full px-3 py-1.5 bg-neutral-100 hover:bg-neutral-200 rounded-md text-sm"
                      onClick={() => loadLayout('Production Focus')}
                    >
                      Load Template
                    </button>
                  </div>
                  
                  <div className="border rounded-lg p-4 hover:border-primary cursor-pointer">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h3 className="font-medium">Analytics Focus</h3>
                        <p className="text-sm text-neutral-dark">Emphasizes AI insights and analytics</p>
                      </div>
                    </div>
                    <div className="bg-neutral-100 h-32 rounded-md mb-3 overflow-hidden">
                      <div className="flex h-full">
                        <div className="w-2/3 p-1">
                          <div className="bg-primary/20 h-6 w-full mb-1 rounded"></div>
                          <div className="bg-primary/40 h-10 w-full mb-1 rounded"></div>
                          <div className="bg-primary/40 h-10 w-full rounded"></div>
                        </div>
                        <div className="w-1/3 p-1">
                          <div className="bg-primary/20 h-8 w-full mb-1 rounded"></div>
                          <div className="bg-primary/20 h-8 w-full mb-1 rounded"></div>
                          <div className="bg-primary/20 h-8 w-full rounded"></div>
                        </div>
                      </div>
                    </div>
                    <button 
                      className="w-full px-3 py-1.5 bg-neutral-100 hover:bg-neutral-200 rounded-md text-sm"
                      onClick={() => loadLayout('Analytics Focus')}
                    >
                      Load Template
                    </button>
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="saved" className="pt-4">
                <div className="text-center py-8">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-neutral-100 mb-3">
                    <span className="material-icons text-neutral-500 text-3xl">bookmark</span>
                  </div>
                  <h3 className="font-medium mb-1">No Saved Layouts</h3>
                  <p className="text-sm text-neutral-dark mb-4">
                    Customize your dashboard and save layouts for different needs
                  </p>
                  <button
                    className="px-4 py-2 bg-primary text-white rounded-md text-sm hover:bg-primary-dark"
                    onClick={() => setIsEditing(true)}
                  >
                    Start Customizing
                  </button>
                </div>
              </TabsContent>
            </Tabs>
          </div>
        )}
      </CardContent>
    </Card>
  );
};