"""Facility module source_module values for vouchers (traceability with posting hooks)."""

SOURCE_FACILITY_DISBURSE = "FACILITY_DISBURSE"
SOURCE_FACILITY_ACCRUAL = "FACILITY_ACCRUAL"
SOURCE_FACILITY_REPAYMENT = "FACILITY_REPAYMENT"
SOURCE_FACILITY_PREPAY = "FACILITY_PREPAY"
SOURCE_FACILITY_SETTLEMENT = "FACILITY_SETTLEMENT"
SOURCE_FACILITY_PENALTY = "FACILITY_PENALTY"
SOURCE_FACILITY_WRITEOFF = "FACILITY_WRITEOFF"
