name: Build and Push Admin UI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-admin/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: prime7biz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-admin
          push: true
          tags: prime7biz/prime7-admin:latest
